language: python
python:
  - "3.6"
before_script:
  - pip install -r test_requirements.txt
  - git clone https://github.com/ibalihikya/maintenance-tracker.git
  - cd maintenance-tracker
  - py.test --cov=api tests/
  - cd -
script:
  - py.test --cov=api /maintenance-tracker/tests/  coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls