language: python
python:
  - "3.6"
before_script:
  - pip install -r requirements.txt
  - git clone https://github.com/ibalihikya/maintenance-tracker.git
  - cd maintenance-tracker
  - py.test --cov=api tests/
  - cd -
script:
  - py.test --cov=api tests/
after_success:
  - coveralls